### ISSUE TITLE
exception can't be caught by tornado

### ISSUE THREAD

**Issue by simpx** [bitly/asyncmongo#10]
def _on_response(self, response, error):
        if error:
            raise tornado.web.HTTPError(500)
##         self.do_something()

the asyncmongo will catch tornado.web.HTTPError and display "callback failed",rather than deliver the exception to tornado.

**Comment by jehiah** [comment]
I believe 3595297a5bd915cc801d5e764b8964a804a0c1ea which i just merged into master will solve this problem

**Comment by simpx** [comment]
thanks! it helps very much:)
