### ISSUE TITLE
Change dbname

### ISSUE THREAD

**Issue by daviesalex** [bitly/asyncmongo#24]
Looking at the example in the README, what happens if you have more than one get() method, and they need to be able to execute async MongoDB queries - but against >1 MongoDB database. With pymongo you can just do connection.db.collection.find(); what is the best way to do this with asyncmongo? Is there a way to set the dbname with a command (such as find/insert etc.)?

**Comment by jehiah** [comment]
`asyncmongo.Client` objects are db specific, but you can just create always another client/connection pool for a different dbname.

**Comment by daviesalex** [comment]
Thanks for confirming.
