### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by steamraven** [bitly/asyncmongo#36]
The connection decrement in ConnectionPool.cache() is NOT thread safe (asyncmongo/pool.py: 129)

It probably needs to be in the lock.

http://effbot.org/pyfaq/what-kinds-of-global-value-mutation-are-thread-safe.htm
http://mail.python.org/pipermail/python-dev/2006-November/thread.html#69981
http://www.velocityreviews.com/forums/t632419-atomic-increment.html

**Comment by jehiah** [comment]
@steamraven asyncmongo isn't really designed to be threadsafe, it's designed to be used in a single thread on a tornado io_loop.
