### ISSUE TITLE
README.md not included with package, results in setuptools error

### ISSUE THREAD

**Issue by kolanos** [bitly/asyncmongo#38]
File ".../env/build/asyncmongo/setup.py", line 11, in <module>

```
long_description=open(os.path.join(os.path.dirname(__file__),"README.md"), "r").read(),
```

IOError: [Errno 2] No such file or directory: '.../env/build/asyncmongo/README.md'

This error is the result of 'pip install asyncmongo'.

**Comment by jehiah** [comment]
thanks. this was a problem with building 1.2 with python2.7 which for some reason is ignoring the manifest file. I've re-built as 1.2.1
