### ISSUE TITLE
Logical Operators:

### ISSUE THREAD

**Issue by JeremyRubin** [bitly/asyncmongo#56]
Hi, 
First off, great project. Thanks for open sourcing it.
Secondly, I can't seem to get logical operators like $or or $and to work. I could always just run my own parallel searches (which is what mongo does anyways I believe) and then logical-or it on my side, but i feel like this should work.

**Comment by jehiah** [comment]
can you provide a snippet of code you've tried using to do an `$or` query?

**Comment by JeremyRubin** [comment]
Sure thing!

``` python
user_instance_queries = {'x':{"$or" : \
[{'x.y': {'$in' : a, other]} },\
{'x.z': {'$in':[b, other]} },\
{'x.p' : {'$in': c,other]} },\
{'x.r': {'$in':[d,other]} } ] },\
'time': {'$in':[time, time+delta,time - delta ] } }
self.db.interations.find( user_instance_queries, {'username':1}, callback=(yield tornado.gen.Callback('user_instance_queries')))
response = yield tornado.gen.Wait('user_instance_queries)
print response
```

returns:

((None,), {'error': DatabaseError(u'database error: invalid operator: $or',)})

**Comment by jehiah** [comment]
I'm not positive, but i think from a quick glance at some spots where i've used `$or`, you need to promote `$or` up one level in your query; you can't nest it under a key. If you do want to apply some additional condition on `x` in your case, you probably need something like `{"$and" [ {"$or": ... }, {"x": ... }]}`

**Comment by JeremyRubin** [comment]
Hey thanks! It worked out perfect for me!

**Comment by eguven** [comment]
Actually @JeremyRubin -if I understood your query correctly-,

```
{"$or": [ {"x.y": {"$in": [ ... ]}},
          {"x.z": {"$in": [ ... ]}},
          ...,
        ],
 "time": { ... }
}
```

would work better. MongoDB QueryOptimizer handles top-level logical operations better.

**Comment by jehiah** [comment]
thanks for the update @JermeyRubin. i'm closing this issue. let us know if you run into anything else
