### ISSUE TITLE
connecting to host with username:password@host.com url

### ISSUE THREAD

**Issue by vikasuy** [bitly/asyncmongo#9]
I'm trying to connect to a mongodb instance being hosted on a remote server. The only way to connect to the host is through the following url:

username:password@host.com

i.e. root:lk3ljkkkajsdfpassword@dkj3kjf.dotcloud.com

asyncmongo reports back an error, 

```
No address associated with hostname
```

Any idea of a fix/workaround to be able to connect?

Thanks!
Vikas

**Comment by vikasuy** [comment]
After doing some research, it seems that this fits into a larger issue of connection to a db with authentication. Is there any plans for supporting this in asyncmongo soon? Something along the lines of what is mentioned here http://www.mongodb.org/display/DOCS/Implementing+Authentication+in+a+Driver . 

Thank for all your help!

**Comment by jehiah** [comment]
vikasuy, there is nothing stopping this from being implemented. I don't personally use authentication, but if you can fork asyncmongo and implement it, I'd be happy to merge that patch in.

**Comment by vikasuy** [comment]
thanks for the info jehiah.

**Comment by patrickod** [comment]
I have implemented Authentication for a fully cached connection pool. The only feature that has yet to be implemented is when a function is called on a connection that has yet to be created we can't block the function and wait until the authentication is finished and as a result the first database request on a new connection will fail. The connection will however be successfully created and authenticated and any subsequent requests against that connection will succeed. Far from ideal but it works for us. 

The fork is here : http://github.com/patrickod/asyncmongo 

We have also changed the method of instantiation to create a cached pool when the server starts and not wait for the first request to create connections.

**Comment by eguven** [comment]
This is an amazing coincidence! I forked this repo hours ago to implement authentication and was working on it at the moment.

**Comment by patrickod** [comment]
Hah that's great. Please fork my fork if it's of any help to you and we can try and finish this last mile of it. :)

**Comment by jehiah** [comment]
@patrickod thanks for working on adding authentication;

After a quick look, i think the remaining work left is to defer the initial query on a new connection that needs authentication, and complete that query after authentication. 

If you could open up a pull request directly to your fork, I'll close this issue in favor of that, and i can give more constructive feedback then.
